"""create users and roles tables

Revision ID: 3295c5f75bd4
Revises: 
Create Date: 2025-10-13 14:20:39.118476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3295c5f75bd4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False, comment='角色ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名稱'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='角色描述'),
    sa.Column('permissions', sa.String(length=1000), nullable=True, comment='權限列表(JSON格式)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='使用者ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='使用者名稱'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='電子郵件'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='加密後的密碼'),
    sa.Column('full_name', sa.String(length=100), nullable=True, comment='真實姓名'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='頭像URL'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='帳號是否啟用'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='是否為超級管理員'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最後登入時間'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新時間'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False, comment='Token ID'),
    sa.Column('token', sa.String(length=500), nullable=False, comment='Refresh Token'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='使用者ID'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='過期時間'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='建立時間'),
    sa.Column('device_info', sa.String(length=200), nullable=True, comment='裝置資訊'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP位址'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
