"""新增訊息附件表 message_attachments

Revision ID: 4940d60afbd9
Revises: 9cc61dc18923
Create Date: 2025-10-30 18:41:38.359692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4940d60afbd9'
down_revision: Union[str, Sequence[str], None] = '9cc61dc18923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 創建 message_attachments 表
    op.create_table(
        'message_attachments',
        sa.Column('id', sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True, nullable=False, comment='附件ID'),
        sa.Column('message_id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False, comment='訊息ID'),
        sa.Column('attachment_type', sa.String(20), nullable=False, comment='附件類型 (image | pdf_page)'),
        sa.Column('file_path', sa.String(500), nullable=False, comment='檔案儲存路徑'),
        sa.Column('original_filename', sa.String(255), nullable=False, comment='原始檔案名稱'),
        sa.Column('file_size', sa.Integer(), nullable=False, comment='檔案大小 (bytes)'),
        sa.Column('mime_type', sa.String(100), nullable=False, comment='MIME 類型'),
        sa.Column('extra_data', sa.JSON(), nullable=False, server_default='{}', comment='附件元資料 (尺寸、頁碼、父檔案等)'),
        sa.Column('processing_status', sa.String(20), nullable=False, server_default='completed', comment='處理狀態 (pending | processing | completed | failed)'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='建立時間'),
        sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    )

    # 創建索引
    op.create_index('ix_message_attachments_message_id', 'message_attachments', ['message_id'], unique=False)
    op.create_index('ix_message_attachments_type', 'message_attachments', ['attachment_type'], unique=False)
    op.create_index('ix_message_attachments_created_at', 'message_attachments', ['created_at'], unique=False)

    # 修改 expert_reviews 索引
    op.drop_index(op.f('idx_expert_reviews_reviewer_created'), table_name='expert_reviews')
    op.create_index('idx_expert_reviews_reviewer_created', 'expert_reviews', ['reviewed_by', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 回退 expert_reviews 索引
    op.drop_index('idx_expert_reviews_reviewer_created', table_name='expert_reviews')
    op.create_index(op.f('idx_expert_reviews_reviewer_created'), 'expert_reviews', ['reviewed_by', sa.literal_column('created_at DESC')], unique=False)

    # 刪除 message_attachments 索引和表
    op.drop_index('ix_message_attachments_created_at', table_name='message_attachments')
    op.drop_index('ix_message_attachments_type', table_name='message_attachments')
    op.drop_index('ix_message_attachments_message_id', table_name='message_attachments')
    op.drop_table('message_attachments')
    # ### end Alembic commands ###
