"""add chat_sessions and chat_messages tables

Revision ID: 51c7351ad40a
Revises: f81a4cb6f73f
Create Date: 2025-10-22 21:43:29.641842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c7351ad40a'
down_revision: Union[str, Sequence[str], None] = 'f81a4cb6f73f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False, comment='Session ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='使用者ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='對話標題'),
    sa.Column('graph_type', sa.String(length=50), nullable=False, comment='Graph 類型 (base_graph | rag_graph | deep_research)'),
    sa.Column('collection_ids', sa.JSON(), nullable=False, comment='選擇的 Collection IDs'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否啟用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新時間'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_sessions_is_active', 'chat_sessions', ['is_active'], unique=False)
    op.create_index('ix_chat_sessions_user_active', 'chat_sessions', ['user_id', 'is_active'], unique=False)
    op.create_index('ix_chat_sessions_user_id', 'chat_sessions', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False, comment='訊息ID'),
    sa.Column('session_id', sa.UUID(), nullable=False, comment='Session ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色 (user | assistant | system)'),
    sa.Column('content', sa.Text(), nullable=False, comment='訊息內容'),
    sa.Column('extra_data', sa.JSON(), nullable=False, comment='元資料 (檢索結果、處理時間等)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='建立時間'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_messages_session_created', 'chat_messages', ['session_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_messages_session_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_chat_sessions_user_id', table_name='chat_sessions')
    op.drop_index('ix_chat_sessions_user_active', table_name='chat_sessions')
    op.drop_index('ix_chat_sessions_is_active', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
