"""Add regulations table for scenarios editor

Revision ID: 699d168a107a
Revises: a1b2c3d4e5f6
Create Date: 2025-11-18 19:56:09.386841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '699d168a107a'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulations',
    sa.Column('id', sa.Integer(), nullable=False, comment='法規ID'),
    sa.Column('law_code', sa.String(length=50), nullable=False, comment='法規代碼（如：D0050001）'),
    sa.Column('law_name', sa.String(length=200), nullable=False, comment='法規名稱'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='法規類別'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='法規狀態（現行/廢止等）'),
    sa.Column('last_updated', sa.String(length=20), nullable=True, comment='最後更新日期（YYYY-MM-DD）'),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='完整法規內容（包含 chapters 和 law_metadata）'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所有者ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新時間'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('law_code')
    )
    op.create_index('ix_regulations_category', 'regulations', ['category'], unique=False)
    op.create_index(op.f('ix_regulations_id'), 'regulations', ['id'], unique=False)
    op.create_index('ix_regulations_law_code', 'regulations', ['law_code'], unique=False)
    op.create_index('ix_regulations_law_name', 'regulations', ['law_name'], unique=False)
    op.create_index('ix_regulations_status', 'regulations', ['status'], unique=False)
    op.create_index('ix_regulations_user_id', 'regulations', ['user_id'], unique=False)
    op.drop_index(op.f('ix_chat_messages_content_recent'), table_name='chat_messages', postgresql_ops={'"left"(content, 1000)': 'text_pattern_ops'})
    op.drop_index(op.f('ix_chat_sessions_created_at'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_title_pattern'), table_name='chat_sessions', postgresql_ops={'title': 'text_pattern_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_sessions_title_pattern'), 'chat_sessions', ['title'], unique=False, postgresql_ops={'title': 'text_pattern_ops'})
    op.create_index(op.f('ix_chat_sessions_created_at'), 'chat_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_content_recent'), 'chat_messages', [sa.literal_column('"left"(content, 1000)')], unique=False, postgresql_ops={'"left"(content, 1000)': 'text_pattern_ops'})
    op.drop_index('ix_regulations_user_id', table_name='regulations')
    op.drop_index('ix_regulations_status', table_name='regulations')
    op.drop_index('ix_regulations_law_name', table_name='regulations')
    op.drop_index('ix_regulations_law_code', table_name='regulations')
    op.drop_index(op.f('ix_regulations_id'), table_name='regulations')
    op.drop_index('ix_regulations_category', table_name='regulations')
    op.drop_table('regulations')
    # ### end Alembic commands ###
