"""add_prompt_templates_table

Revision ID: 823cda381a78
Revises: 24df578b8fec
Create Date: 2025-11-20 12:40:11.852533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '823cda381a78'
down_revision: Union[str, Sequence[str], None] = '24df578b8fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_templates',
    sa.Column('id', sa.UUID(), nullable=False, comment='主鍵'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='使用者 ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='提示詞名稱'),
    sa.Column('content', sa.Text(), nullable=False, comment='提示詞內容（最多 5000 字）'),
    sa.Column('description', sa.Text(), nullable=True, comment='提示詞描述'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否為使用者的預設提示詞'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否啟用（軟刪除）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新時間'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_templates_user_id'), 'prompt_templates', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_templates_user_id'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    # ### end Alembic commands ###
