"""Add created_at indexes to chat_messages and chat_sessions for dashboard performance

Revision ID: 8329989679e2
Revises: 996f19ee635f
Create Date: 2025-11-26 19:25:57.594932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8329989679e2'
down_revision: Union[str, Sequence[str], None] = '996f19ee635f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_chat_messages_created_at', 'chat_messages', ['created_at'], unique=False)
    op.create_index('ix_chat_sessions_created_at', 'chat_sessions', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_sessions_created_at', table_name='chat_sessions')
    op.drop_index('ix_chat_messages_created_at', table_name='chat_messages')
    # ### end Alembic commands ###
