"""add chat search indexes

Revision ID: a1b2c3d4e5f6
Revises: 4940d60afbd9
Create Date: 2025-11-13 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '4940d60afbd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. 為 chat_sessions.created_at 建立索引（用於時間範圍過濾）
    op.create_index(
        'ix_chat_sessions_created_at',
        'chat_sessions',
        ['created_at'],
        unique=False
    )

    # 2. 為 chat_sessions.title 建立索引（支援 ILIKE 查詢）
    # 使用 text_pattern_ops 優化 LIKE/ILIKE 查詢效能
    op.execute("""
        CREATE INDEX ix_chat_sessions_title_pattern
        ON chat_sessions (title text_pattern_ops)
    """)

    # 3. 為 chat_messages.content 建立索引（支援 ILIKE 查詢）
    # 注意：使用 LEFT(content, 1000) 限制索引大小，而非使用部分索引的 WHERE 條件
    # 原因：PostgreSQL 要求部分索引的 WHERE 條件必須使用 IMMUTABLE 函數
    # CURRENT_DATE - INTERVAL '6 months' 包含 CURRENT_DATE（STABLE 函數），會導致錯誤：
    # "functions in index predicate must be marked IMMUTABLE"
    # 因此改用 LEFT() 函數限制索引長度，時間過濾在應用層實現
    op.execute("""
        CREATE INDEX ix_chat_messages_content_recent
        ON chat_messages (LEFT(content, 1000) text_pattern_ops)
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 刪除索引（按建立順序的反向）
    op.execute("DROP INDEX IF EXISTS ix_chat_messages_content_recent")
    op.execute("DROP INDEX IF EXISTS ix_chat_sessions_title_pattern")
    op.drop_index('ix_chat_sessions_created_at', table_name='chat_sessions')

    # ### end Alembic commands ###
