"""add message_feedback table

Revision ID: dd5e9e4400da
Revises: 51c7351ad40a
Create Date: 2025-10-28 15:42:06.384468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd5e9e4400da'
down_revision: Union[str, Sequence[str], None] = '51c7351ad40a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_feedbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False, comment='關聯的訊息 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='提交反饋的使用者 ID'),
    sa.Column('feedback_type', sa.Enum('THUMBS_UP', 'THUMBS_DOWN', name='feedback_type_enum'), nullable=False, comment='反饋類型: thumbs_up 或 thumbs_down'),
    sa.Column('issue_tags', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment="問題標籤列表,如 ['回答不準確', '內容太簡短']"),
    sa.Column('comment', sa.Text(), nullable=True, comment='使用者自由填寫的評論'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='反饋建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='反饋最後更新時間'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_message_user_feedback')
    )
    op.create_index('idx_feedback_created_at', 'message_feedbacks', ['created_at'], unique=False)
    op.create_index('idx_feedback_message_user', 'message_feedbacks', ['message_id', 'user_id'], unique=False)
    op.create_index('idx_feedback_type', 'message_feedbacks', ['feedback_type'], unique=False)
    op.create_index(op.f('ix_message_feedbacks_id'), 'message_feedbacks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_feedbacks_id'), table_name='message_feedbacks')
    op.drop_index('idx_feedback_type', table_name='message_feedbacks')
    op.drop_index('idx_feedback_message_user', table_name='message_feedbacks')
    op.drop_index('idx_feedback_created_at', table_name='message_feedbacks')
    op.drop_table('message_feedbacks')
    # ### end Alembic commands ###
